server:
  port: 8080
  servlet:
    context-path: /easybuy
    #数据源配置
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/easybuy?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
    #热部署配置
  devtools:
    restart:
      enabled: true
      #设置重启目录
      additional-paths: src/main/java
      #解决项目重新编译后报404问题
      poll-interval: 3000
      quiet-period: 1000
      #添加Ehcache配置
  cache:
    ehcache:
      config: classpath:ehcache.xml
  #freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
    request-context-attribute: request
    expose-request-attributes: true
    expose-spring-macro-helpers: true


  #mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.xu.pojo
  configuration:
    ##下划线转驼峰配置
    map-underscore-to-camel-case: true
    #配置PageHelper
pagehelper:
  helper-dialect: mysql
  #显示dao，执行sql语句
logging:
  level:
    com:
      xu:
        springboot:
          dao: debug

